# torchcell/candidates/ledger.py
# [[torchcell.candidates.ledger]]
# https://github.com/Mjvolk3/torchcell/tree/main/torchcell/candidates/ledger.py
# Test file: tests/torchcell/candidates/test_ledger.py
"""Render the verdict store as a dated section of ``notes/torchcell.candidates.ledger.md``.

The ledger is generated, never hand-edited: one Markdown table per run, appended as a
``## YYYY.MM.DD - Candidate gate ledger`` section so the note keeps every earlier state
(the dendron date-section convention). The table follows the ``markdown_table`` pattern of
``experiments/036-dataset-fixes-before-kg-build/scripts/si_audit_loadable_ledger.py``.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Final

from torchcell.candidates.verdict import CandidateVerdict

REPO: Final = Path(__file__).resolve().parents[2]
LEDGER_NOTE: Final = REPO / "notes" / "torchcell.candidates.ledger.md"

#: One glyph per gate outcome, the legend printed above every table.
GLYPH: Final[dict[str, str]] = {
    "pass": "✓",
    "fail": "✗",
    "blocked": "■",
    "gap": "◐",
    "unmeasured": "·",
}
LEGEND: Final = (
    "Gates: ✓ pass, ✗ fail, ■ blocked, ◐ gap (issue filed), · unmeasured. "
    "Generated by `python -m torchcell.candidates ledger` from `database/candidates/`; "
    "do not edit by hand."
)
HEADER: Final = (
    "| citation key | table | row | G1 | G2 | G3 | G4 | G5 | outcome | issue | "
    "decided | commit |\n"
    "|---|---|---|---|---|---|---|---|---|---|---|---|"
)


def heading(date: str) -> str:
    """``## YYYY.MM.DD - Candidate gate ledger`` from an ISO date."""
    if len(date) != 10 or date[4] != "-" or date[7] != "-":
        raise ValueError(f"not an ISO date: {date!r}")
    return f"## {date.replace('-', '.')} - Candidate gate ledger"


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render_row(verdict: CandidateVerdict) -> str:
    """One table row: key, table, row, the five glyphs, outcome, issues, date, commit."""
    glyphs = " | ".join(GLYPH[g.outcome] for g in verdict.gates)
    issues = ", ".join(f"#{g.issue}" for g in verdict.gates if g.issue is not None)
    return (
        f"| {verdict.citation_key} | {verdict.table} | {_cell(verdict.row_name)} | "
        f"{glyphs} | **{verdict.outcome}** | {issues} | {verdict.decided_at[:10]} | "
        f"`{verdict.torchcell_commit[:9]}` |"
    )


def render_section(verdicts: Iterable[CandidateVerdict], date: str) -> str:
    """The dated section: heading, legend, and the table sorted by table then row."""
    rows = sorted(verdicts, key=lambda v: (v.table, v.row_name, v.citation_key))
    body = "\n".join([HEADER, *(render_row(v) for v in rows)])
    return f"{heading(date)}\n\n{LEGEND}\n\n{body}\n"


def append_section(note: Path, section: str) -> None:
    """Append ``section`` to the note; a section with the same heading already there raises."""
    text = note.read_text(encoding="utf-8")
    first_line = section.split("\n", 1)[0]
    if any(line == first_line for line in text.splitlines()):
        raise ValueError(f"{note.name} already has {first_line!r}; one ledger per day")
    separator = (
        "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    )
    note.write_text(text + separator + section, encoding="utf-8")
