# notes-tex/perturbation-operator/Makefile
# [[experiments.019-simb-multimodal.multiplicative-perturbation-conditioning]]
# https://github.com/Mjvolk3/torchcell/tree/main/notes-tex/perturbation-operator/Makefile

DOC := perturbation-operator

# No Zotero collection and no \cite: external papers are named inline with their DOI and
# flagged \external. `make bib` is therefore not available here; `make check` still runs.
ZOTERO_COLLECTION          :=
ZOTERO_PERSONAL_COLLECTION :=

PYTHON ?= /home/michaelvolk/miniconda3/envs/torchcell/bin/python

include ../common/Makefile.common
