from intermine.webservice import Service as Service
from math import log as log

def save_mine_and_token(m, t): ...
def plot_go_vs_p(list_name) -> None: ...
def plot_go_vs_count(list_name) -> None: ...
def get_query(xml): ...
def query_to_barchart_log(xml, resp) -> None: ...
