from _typeshed import Incomplete
from intermine.webservice import Service as Service

def getVersion(mine): ...
def getInfo(mine): ...
def getData(mine): ...
def getMines(organism: Incomplete | None = ...): ...
