# tests/torchcell/literature/test_bib_store.py
"""Tests for the served bibliography store (export side) and its /bib endpoint.

Zotero is never contacted: the pull is monkeypatched to return canned entries, so
what is exercised is spec discovery from the repo's Makefiles, the atomic write +
manifest, the content-stable hash, and the endpoint's hash header.
"""

import hashlib
from pathlib import Path
from typing import Any, cast

import pytest
from fastapi.testclient import TestClient

import torchcell.literature.bib_store as store_mod
from torchcell.literature.bib_store import (
    BIB_STORE_MANIFEST,
    BibScope,
    BibSpec,
    BibStoreManifest,
    bib_store_dir,
    discover_bib_specs,
    export_bib_store,
    load_bib_store,
    parse_makefile_collections,
    validate_bib_name,
)
from torchcell.literature.server import (
    LiteratureKeys,
    LiteratureServerConfig,
    create_app,
)
from torchcell.literature.zotero import ZoteroLibrary

KEY = "test-key"
HEADERS = {"X-API-Key": KEY}
# The pull is monkeypatched, so no library is ever touched.
NO_LIB = cast(ZoteroLibrary, None)
Canned = dict[str, list[dict[str, Any]]]


def _entry(key: str, title: str) -> dict[str, str]:
    return {
        "ID": key,
        "ENTRYTYPE": "article",
        "author": "Zotero, Zed",
        "title": title,
        "year": "2020",
    }


def _spec(name: str, **scope: str) -> BibSpec:
    return BibSpec(
        name=name, scope=BibScope(group_library_id="6582362", **scope), origin="test"
    )


@pytest.fixture
def fake_repo(tmp_path: Path) -> Path:
    """A repo skeleton with two notes-tex documents, one of which cites nothing."""
    cited = tmp_path / "notes-tex" / "eqtl-data-model"
    cited.mkdir(parents=True)
    (cited / "Makefile").write_text(
        "ZOTERO_COLLECTION          := VNDH4NMX\n"
        "ZOTERO_PERSONAL_COLLECTION := 4VNJWJAW\n"
        "include ../common/Makefile.common\n"
    )
    silent = tmp_path / "notes-tex" / "w019-strain-build-list"
    silent.mkdir(parents=True)
    (silent / "Makefile").write_text(
        "# No ZOTERO_COLLECTION: the document cites nothing\n"
        "include ../common/Makefile.common\n"
    )
    return tmp_path


@pytest.fixture
def canned_pull(monkeypatch: pytest.MonkeyPatch) -> dict[str, list[dict[str, Any]]]:
    """Replace the Zotero pull with a per-name canned response."""
    canned: dict[str, list[dict[str, Any]]] = {}

    def fake_fetch(scope: BibScope, group: Any, user: Any) -> list[dict[str, Any]]:
        return canned[scope.group_collection or "*"]

    monkeypatch.setattr(store_mod, "fetch_scope_entries", fake_fetch)
    return canned


def test_parse_makefile_collections(fake_repo: Path) -> None:
    makefile = fake_repo / "notes-tex" / "eqtl-data-model" / "Makefile"
    assert parse_makefile_collections(makefile) == ("VNDH4NMX", "4VNJWJAW")
    silent = fake_repo / "notes-tex" / "w019-strain-build-list" / "Makefile"
    assert parse_makefile_collections(silent) == ("", "")


def test_discover_specs_reads_repo_declarations(fake_repo: Path) -> None:
    specs = discover_bib_specs(
        fake_repo, group_library_id="6582362", user_library_id="1234"
    )
    by_name = {s.name: s for s in specs}
    # paper first, library last, one per citing notes-tex document in between.
    assert [s.name for s in specs] == ["paper", "eqtl-data-model", "library"]
    assert by_name["paper"].scope.group_collection == "W46ATS7B"
    assert by_name["paper"].scope.user_collection is None
    doc = by_name["eqtl-data-model"].scope
    assert (doc.group_collection, doc.user_collection) == ("VNDH4NMX", "4VNJWJAW")
    assert doc.user_library_id == "1234"
    assert by_name["eqtl-data-model"].origin == "notes-tex/eqtl-data-model/Makefile"
    assert by_name["library"].scope.user_root_collection == "torchcell"


def test_name_validation_rejects_path_separators() -> None:
    assert validate_bib_name("024-perturb-seq-costing") == "024-perturb-seq-costing"
    for bad in ("../x", "a/b", ".hidden", ""):
        with pytest.raises(ValueError):
            validate_bib_name(bad)


def test_export_writes_files_and_manifest(tmp_path: Path, canned_pull: Canned) -> None:
    canned_pull["W46ATS7B"] = [_entry("b2020", "Second"), _entry("a2020", "First")]
    spec = _spec("paper", group_collection="W46ATS7B")

    manifest = export_bib_store(tmp_path, [spec], NO_LIB, NO_LIB, generated_at="T0")

    store = bib_store_dir(tmp_path)
    text = (store / "paper.bib").read_text()
    assert text.startswith("% GENERATED by torchcell.literature.bib_store")
    assert "% scope: group 6582362/W46ATS7B" in text
    assert text.index("a2020") < text.index("b2020")  # sorted by key
    assert not list(store.glob("*.part"))
    record = manifest.get("paper")
    assert record is not None
    assert record.n_entries == 2
    assert record.sha256 == hashlib.sha256(text.encode()).hexdigest()
    assert load_bib_store(tmp_path) == manifest
    assert (store / BIB_STORE_MANIFEST).is_file()


def test_export_is_content_stable_across_runs(
    tmp_path: Path, canned_pull: Canned
) -> None:
    """Same entries on a later date -> same bytes and sha256; only the stamp moves."""
    canned_pull["W46ATS7B"] = [_entry("a2020", "First")]
    spec = _spec("paper", group_collection="W46ATS7B")
    first = export_bib_store(tmp_path, [spec], NO_LIB, NO_LIB, generated_at="T0")
    second = export_bib_store(tmp_path, [spec], NO_LIB, NO_LIB, generated_at="T1")
    a, b = first.get("paper"), second.get("paper")
    assert a is not None and b is not None
    assert a.sha256 == b.sha256
    assert second.generated_at == "T1"


def test_export_refuses_empty_pull_and_keeps_previous_store(
    tmp_path: Path, canned_pull: Canned
) -> None:
    """A 0-entry pull raises before the served files or manifest change."""
    canned_pull["W46ATS7B"] = [_entry("a2020", "First")]
    spec = _spec("paper", group_collection="W46ATS7B")
    before = export_bib_store(tmp_path, [spec], NO_LIB, NO_LIB, generated_at="T0")

    canned_pull["W46ATS7B"] = []
    with pytest.raises(RuntimeError, match="0 entries"):
        export_bib_store(tmp_path, [spec], NO_LIB, NO_LIB, generated_at="T1")

    assert load_bib_store(tmp_path) == before
    assert not list(bib_store_dir(tmp_path).glob("*.part"))


def test_partial_failure_leaves_previous_store_intact(
    tmp_path: Path, canned_pull: Canned
) -> None:
    """If the second spec fails, the first spec's new file is NOT swapped in."""
    canned_pull["W46ATS7B"] = [_entry("a2020", "First")]
    canned_pull["VNDH4NMX"] = [_entry("q2020", "Doc")]
    paper = _spec("paper", group_collection="W46ATS7B")
    doc = _spec("eqtl-data-model", group_collection="VNDH4NMX")
    before = export_bib_store(tmp_path, [paper, doc], NO_LIB, NO_LIB, generated_at="T0")

    canned_pull["W46ATS7B"] = [_entry("a2020", "First"), _entry("z2021", "Added")]
    canned_pull["VNDH4NMX"] = []
    with pytest.raises(RuntimeError):
        export_bib_store(tmp_path, [paper, doc], NO_LIB, NO_LIB, generated_at="T1")

    assert load_bib_store(tmp_path) == before
    paper_text = (bib_store_dir(tmp_path) / "paper.bib").read_text()
    assert "z2021" not in paper_text


# --- endpoint -----------------------------------------------------------------


@pytest.fixture
def client(tmp_path: Path, canned_pull: Canned) -> TestClient:
    (tmp_path / "fakePaperKey2020").mkdir()
    (tmp_path / "_sync_reports").mkdir()
    canned_pull["W46ATS7B"] = [_entry("a2020", "First")]
    export_bib_store(
        tmp_path, [_spec("paper", group_collection="W46ATS7B")], NO_LIB, NO_LIB
    )
    config = LiteratureServerConfig(
        mirror_root=tmp_path, keys=LiteratureKeys.from_pairs(f"t:{KEY}"), port=8899
    )
    return TestClient(create_app(config))


def test_service_dirs_are_not_citation_keys(client: TestClient) -> None:
    assert client.get("/keys", headers=HEADERS).json()["citation_keys"] == [
        "fakePaperKey2020"
    ]
    health = client.get("/health").json()
    assert health["n_keys"] == 1
    assert health["n_bibs"] == 1


def test_bib_listing_is_the_store_manifest(client: TestClient) -> None:
    assert client.get("/bib").status_code == 401
    resp = client.get("/bib", headers=HEADERS)
    assert resp.status_code == 200
    manifest = BibStoreManifest.model_validate(resp.json())
    assert [b.name for b in manifest.bibs] == ["paper"]


def test_bib_download_matches_manifest_sha256(client: TestClient) -> None:
    record = BibStoreManifest.model_validate(
        client.get("/bib", headers=HEADERS).json()
    ).get("paper")
    assert record is not None
    resp = client.get("/bib/paper", headers=HEADERS)
    assert resp.status_code == 200
    assert resp.headers["X-Artifact-SHA256"] == record.sha256
    assert hashlib.sha256(resp.content).hexdigest() == record.sha256
    assert b"@article{a2020" in resp.content


def test_bib_unknown_and_illegal_names(client: TestClient) -> None:
    assert client.get("/bib/nope", headers=HEADERS).status_code == 404
    assert client.get("/bib/..%2Fmanifest.json", headers=HEADERS).status_code in (
        400,
        404,
    )


def test_bib_404_when_no_store(tmp_path: Path) -> None:
    config = LiteratureServerConfig(
        mirror_root=tmp_path, keys=LiteratureKeys.from_pairs(f"t:{KEY}"), port=8899
    )
    c = TestClient(create_app(config))
    assert c.get("/bib", headers=HEADERS).status_code == 404
    assert c.get("/health").json()["n_bibs"] == 0
