# notes-tex/w019-strain-build-list/Makefile
# [[experiments.W019-echo-crispr-array.build-list]]
# https://github.com/Mjvolk3/torchcell/tree/main/notes-tex/w019-strain-build-list/Makefile
#
# No ZOTERO_COLLECTION: the document cites nothing, so there is no collection to
# export and `make bib` is not meant to run here. references.bib is an empty
# placeholder because the shared build rules list it as a prerequisite.
#
# No PYTHON override either. The default `python` from ../common/Makefile.common
# is only used by `make check`, which needs the standard library and nothing else.

include ../common/Makefile.common
