# notes-tex/eqtl-data-model/Makefile
# [[torchcell.datamodels.eqtl-data-model]]
# https://github.com/Mjvolk3/torchcell/tree/main/notes-tex/eqtl-data-model/Makefile
#
# No ZOTERO_COLLECTION: sources are carried as resolvable links in the prose rather
# than \cite keys, so there is no collection to export and `make bib` is not meant to
# run here. references.bib is an empty placeholder because the shared build rules list
# it as a prerequisite. Same arrangement as notes-tex/w019-strain-build-list.
#
# The figure is exported from notes/assets/drawio/ by `make figures`.

PYTHON ?= /home/michaelvolk/miniconda3/envs/torchcell/bin/python
DRAWIO ?= /tmp/drawio-exec.AppImage

include ../common/Makefile.common
