
biocypher:
  offline: true
  debug: false
  schema_config_path: config/torchcell_schema_config.yaml
  cache_directory: .cache

neo4j:
  delimiter: '\t'
  array_delimiter: '|'
  skip_duplicate_nodes: true
  skip_bad_relationships: true

  # Wipe DB before import (offline mode: --force)
  wipe: true

  database_name: torchcell
  uri: neo4j://localhost:7687
  user: neo4j
  password: neo4j