
biocypher:
  offline: true
  debug: false
  schema_config_path: config/torchcell_schema_config.yaml
  cache_directory: .cache

neo4j:
  delimiter: '\t'
  array_delimiter: '|'
  skip_duplicate_nodes: true
  skip_bad_relationships: true
