"""General-purpose helpers: numeric formatting, and the repo-wide figure/plot
standards (ordered palette, Nature panel widths, true-size SVG export).
"""

import math
import re
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from matplotlib.figure import Figure

# --- Repo-wide figure/plotting standards. See CLAUDE.md "Figure & Plotting
# Standards" and the palette notes/assets/images/color-palette.svg. -----------
MAX_HEIGHT_MM = 170.0  # Nature single-figure max height (loose cap)
PANEL_WIDTHS_MM = {
    "full": 179.0,  # 1 across (safety margin under Nature's 180 mm)
    "wide": 118.9,  # wide panel of an asymmetric pair (with "third")
    "half_plus": 88.5,  # 2 across (slightly generous half)
    "half": 88.0,  # 2 across (= Nature single-column width)
    "third": 57.8,  # 3 across
    "sixth": 28.3,  # 6 across (smallest)
}


def mm_to_in(mm: float) -> float:
    """Millimeters -> inches, for matplotlib ``figsize`` at true physical size."""
    return mm / 25.4


# Single ordered qualitative plot palette (green-free), as draw.io-style
# (line/stroke, fill) PAIRS -- the same object colors used in Fig 1 (light fill +
# bold darker line). Assign in order: the four warm primaries (orange/red/purple/
# yellow) FIRST, then blue, gray, then darker variants; blue/gray are not used until
# the four primaries are used up. PLOT_PALETTE = line/stroke colors (lines, markers,
# bar edges & hatches); PLOT_PALETTE_FILL = matching light fills (bar/marker faces).
# A simple N-category series takes the first N of each. Visual reference:
# notes/assets/images/color-palette.svg (generated by generate_color_palette.py).
PLOT_PALETTE = [
    "#D79B00",  # 1  amber        [orange slot, primary, draw.io]
    "#B85450",  # 2  brick        [red slot, primary, draw.io]
    "#9673A6",  # 3  lilac        [purple slot, primary, draw.io]
    "#D6B656",  # 4  wheat        [yellow slot, primary, draw.io]
    "#6C8EBF",  # 5  steel blue   [blue slot, primary, draw.io]
    "#666666",  # 6  gray         [gray slot, primary, draw.io]
    "#9D7100",  # 7  bronze       [orange slot, dark]
    "#863D3A",  # 8  maroon       [red slot, dark]
    "#6E5479",  # 9  plum         [purple slot, dark]
    "#9C853F",  # 10 old gold     [yellow slot, dark]
    "#4F688B",  # 11 denim        [blue slot, dark]
    "#4A4A4A",  # 12 charcoal     [gray slot, dark]
    "#C48161",  # 13 terracotta   [orange slot, muted earth]
    "#9A6B66",  # 14 rose brown   [red slot, muted earth]
    "#B690A4",  # 15 dusty mauve  [purple slot, muted earth]
    "#D2AE7D",  # 16 sand         [yellow slot, muted earth]
    "#899EAB",  # 17 slate        [blue slot, muted earth]
    "#A29682",  # 18 taupe        [gray slot, muted earth]
]
PLOT_PALETTE_FILL = [
    "#FFE6CC",  # 1  amber        [orange slot, primary, draw.io]
    "#F8CECC",  # 2  brick        [red slot, primary, draw.io]
    "#E1D5E7",  # 3  lilac        [purple slot, primary, draw.io]
    "#FFF2CC",  # 4  wheat        [yellow slot, primary, draw.io]
    "#DAE8FC",  # 5  steel blue   [blue slot, primary, draw.io]
    "#F5F5F5",  # 6  gray         [gray slot, primary, draw.io]
    "#F3D08F",  # 7  bronze       [orange slot, dark]
    "#E5A9A7",  # 8  maroon       [red slot, dark]
    "#CAB8D4",  # 9  plum         [purple slot, dark]
    "#F3E0A9",  # 10 old gold     [yellow slot, dark]
    "#B9CDEA",  # 11 denim        [blue slot, dark]
    "#CACACA",  # 12 charcoal     [gray slot, dark]
    "#F9D0BE",  # 13 terracotta   [orange slot, muted earth]
    "#EFD2CF",  # 14 rose brown   [red slot, muted earth]
    "#E8D3DE",  # 15 dusty mauve  [purple slot, muted earth]
    "#EBD6BC",  # 16 sand         [yellow slot, muted earth]
    "#CFDAE1",  # 17 slate        [blue slot, muted earth]
    "#DFD8CD",  # 18 taupe        [gray slot, muted earth]
]

# The TRUE name of each color. The SLOT (index % 6 -> orange/red/purple/yellow/blue/gray)
# is what drives assignment ORDER, but the muted tier is not literally those hues: #18 sits
# in the gray slot and is a taupe, #13 is a terracotta, #16 is a sand. Labelling a swatch
# with its slot was simply wrong. Use these for legends and swatch labels.
PLOT_PALETTE_NAMES = [
    "amber",  # 1
    "brick",  # 2
    "lilac",  # 3
    "wheat",  # 4
    "steel blue",  # 5
    "gray",  # 6
    "bronze",  # 7
    "maroon",  # 8
    "plum",  # 9
    "old gold",  # 10
    "denim",  # 11
    "charcoal",  # 12
    "terracotta",  # 13
    "rose brown",  # 14
    "dusty mauve",  # 15
    "sand",  # 16
    "slate",  # 17
    "taupe",  # 18
]

# Display-name overrides for node representations, applied ONLY at plot-label time; the
# data keys / model names in code stay unchanged. `fudt_*` is torchcell's internal name for
# the Gagneur-lab species-aware DNA language model (HuggingFace gagneurlab/SpeciesLM), which
# the paper refers to as "Species LM"; underscore style keeps it consistent with the other
# raw feature labels (e.g. codon_frequency). Single source of truth -- edit here, not per
# script.
REPRESENTATION_DISPLAY_NAMES: dict[str, str] = {
    # upstream = 5' region, downstream = 3'; written out with underscores to match the
    # nucleotide-transformer labels (nt_window_five_prime_*). No size suffix: SpeciesLM is
    # not a size we chose (unlike the NT windows), so we do not annotate one.
    "fudt_upstream": "species_lm_five_prime",
    "fudt_downstream": "species_lm_three_prime",
}


def display_label(name: str) -> str:
    """Map an internal representation key to its plot-display label (identity if unmapped)."""
    return REPRESENTATION_DISPLAY_NAMES.get(name, name)


def savefig_true_size_svg(
    fig: "Figure",
    path: str,
    src_dpi: int = 72,
    drawio_dpi: int = 100,
    **savefig_kwargs: Any,
) -> None:
    """Save a matplotlib figure as an SVG that imports at TRUE physical size in draw.io.

    matplotlib writes SVG coordinates in PostScript points (72 per inch) and tags the
    root ``width``/``height`` with the ``pt`` unit. draw.io does not honor the CSS
    definition of ``pt``; it reads the numeric ``width``/``height``/``viewBox`` in its
    own native unit of 100 per inch. A figure authored at W inches therefore imports at
    ``W * 72/100`` inches -- 72% of intended, fonts included (the source of the
    57.7 mm-file / 41.4 mm-in-draw.io discrepancy).

    This saves the SVG, then rewrites the root so the coordinate numbers correspond to
    ``drawio_dpi`` (100) per inch and wraps the drawn content in a matching ``scale()``
    group. The rendered result is visually identical; only the declared coordinate
    system changes, so draw.io lands on the true mm/pt sizes and 6 pt text stays 6 pt.

    For a fixed-figsize WYSIWYG canvas, do NOT pass ``bbox_inches="tight"`` -- it
    recrops the canvas and defeats the intended size; author the figure at its final
    ``figsize`` instead. It IS appropriate for a standalone figure whose goal is a
    tight crop (e.g. a legend-only image); the rescale still yields a correct
    physical size for whatever tight box matplotlib emits.
    """
    fig.savefig(path, **savefig_kwargs)
    with open(path, encoding="utf-8") as f:
        svg = f.read()
    # matplotlib always emits an <svg> root tagged with width/height in pt. If any of
    # these is missing the file is not a matplotlib SVG and the rescale is meaningless,
    # so fail loudly rather than silently writing a wrongly-sized figure.
    m_tag = re.search(r"<svg\b[^>]*>", svg)
    if m_tag is None:
        raise ValueError(f"{path}: no <svg> root tag; not a matplotlib SVG")
    open_tag = m_tag.group(0)
    m_w = re.search(r'width="([\d.]+)pt"', open_tag)
    m_h = re.search(r'height="([\d.]+)pt"', open_tag)
    if m_w is None or m_h is None:
        raise ValueError(f"{path}: <svg> root has no pt width/height to rescale")
    w = float(m_w.group(1))
    h = float(m_h.group(1))
    k = drawio_dpi / src_dpi
    new_w, new_h = w * k, h * k
    new_tag = re.sub(r'width="[\d.]+pt"', f'width="{new_w:.4f}"', open_tag)
    new_tag = re.sub(r'height="[\d.]+pt"', f'height="{new_h:.4f}"', new_tag)
    new_tag = re.sub(
        r'viewBox="[^"]*"', f'viewBox="0 0 {new_w:.4f} {new_h:.4f}"', new_tag
    )
    svg = svg.replace(open_tag, new_tag + f'<g transform="scale({k:.10f})">', 1)
    svg = svg.replace("</svg>", "</g></svg>", 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(svg)


def format_scientific_notation(num: float) -> str:
    """Format a number into scientific notation, preserving all significant digits.

    Examples:
        10000 -> "1e04"
        10007 -> "1.0007e04"
        1234567 -> "1.234567e06"
        100 -> "1e02"
    """
    if num == 0:
        return "0"

    # Handle negative numbers
    sign = ""
    if num < 0:
        sign = "-"
        num = abs(num)

    # Get exponent (power of 10)
    exponent = int(math.floor(math.log10(num)))
    mantissa = num / (10**exponent)

    # Find minimum precision needed to preserve the exact value
    mantissa_str = f"{mantissa:.0f}"  # Default for Pylance
    for precision in range(15):
        mantissa_str = f"{mantissa:.{precision}f}"
        reconstructed = float(mantissa_str) * (10**exponent)
        if round(reconstructed) == round(num):
            break

    # Clean up: remove trailing zeros and unnecessary decimal point
    mantissa_str = mantissa_str.rstrip("0").rstrip(".")

    return f"{sign}{mantissa_str}e{exponent:02d}"
