"""General-purpose helpers: numeric formatting, and the repo-wide figure/plot
standards (ordered palette, Nature panel widths, true-size SVG export).
"""

import math
import re
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from matplotlib.figure import Figure

# --- Repo-wide figure/plotting standards. See CLAUDE.md "Figure & Plotting
# Standards" and the palette notes/assets/images/color-palette.svg. -----------
MAX_HEIGHT_MM = 170.0  # Nature single-figure max height (loose cap)
PANEL_WIDTHS_MM = {
    "full": 179.0,  # 1 across (safety margin under Nature's 180 mm)
    "wide": 118.9,  # wide panel of an asymmetric pair (with "third")
    "half_plus": 88.5,  # 2 across (slightly generous half)
    "half": 88.0,  # 2 across (= Nature single-column width)
    "third": 57.8,  # 3 across
    "sixth": 28.3,  # 6 across (smallest)
}


def mm_to_in(mm: float) -> float:
    """Millimeters -> inches, for matplotlib ``figsize`` at true physical size."""
    return mm / 25.4


# Single ordered qualitative plot palette (green-free), as draw.io-style
# (line/stroke, fill) PAIRS -- the same object colors used in Fig 1 (light fill +
# bold darker line). Assign in order: the four warm primaries (orange/red/purple/
# yellow) FIRST, then blue, gray, then darker variants; blue/gray are not used until
# the four primaries are used up. PLOT_PALETTE = line/stroke colors (lines, markers,
# bar edges & hatches); PLOT_PALETTE_FILL = matching light fills (bar/marker faces).
# A simple N-category series takes the first N of each. Visual reference:
# notes/assets/images/color-palette.svg (generated by generate_color_palette.py).
PLOT_PALETTE = [
    "#D79B00",  # 1  orange  (primary, draw.io)
    "#B85450",  # 2  red     (primary, draw.io)
    "#9673A6",  # 3  purple  (primary, draw.io)
    "#D6B656",  # 4  yellow  (primary, draw.io)
    "#6C8EBF",  # 5  blue    (secondary, draw.io)
    "#666666",  # 6  gray    (secondary, draw.io)
    "#9D7100",  # 7  orange  (dark)
    "#863D3A",  # 8  red     (dark)
    "#6E5479",  # 9  purple  (dark)
    "#9C853F",  # 10 yellow  (dark)
    "#4F688B",  # 11 blue    (dark)
    "#4A4A4A",  # 12 gray    (dark)
    "#C08552",  # 13 orange  (burnt)
    "#A85878",  # 14 red     (mauve)
    "#9C6EA0",  # 15 purple  (light)
    "#6E93B8",  # 16 blue    (steel)
    "#B5943F",  # 17 yellow  (ochre)
]
PLOT_PALETTE_FILL = [
    "#FFE6CC",  # 1  orange
    "#F8CECC",  # 2  red
    "#E1D5E7",  # 3  purple
    "#FFF2CC",  # 4  yellow
    "#DAE8FC",  # 5  blue
    "#F5F5F5",  # 6  gray
    "#F3D08F",  # 7  orange
    "#E5A9A7",  # 8  red
    "#CAB8D4",  # 9  purple
    "#F3E0A9",  # 10 yellow
    "#B9CDEA",  # 11 blue
    "#CACACA",  # 12 gray
    "#ECDAC5",  # 13 orange
    "#E5CDD7",  # 14 red
    "#E1D4E3",  # 15 purple
    "#D4DFEA",  # 16 blue
    "#E9DFC5",  # 17 yellow
]


def savefig_true_size_svg(
    fig: "Figure",
    path: str,
    src_dpi: int = 72,
    drawio_dpi: int = 100,
    **savefig_kwargs: Any,
) -> None:
    """Save a matplotlib figure as an SVG that imports at TRUE physical size in draw.io.

    matplotlib writes SVG coordinates in PostScript points (72 per inch) and tags the
    root ``width``/``height`` with the ``pt`` unit. draw.io does not honor the CSS
    definition of ``pt``; it reads the numeric ``width``/``height``/``viewBox`` in its
    own native unit of 100 per inch. A figure authored at W inches therefore imports at
    ``W * 72/100`` inches -- 72% of intended, fonts included (the source of the
    57.7 mm-file / 41.4 mm-in-draw.io discrepancy).

    This saves the SVG, then rewrites the root so the coordinate numbers correspond to
    ``drawio_dpi`` (100) per inch and wraps the drawn content in a matching ``scale()``
    group. The rendered result is visually identical; only the declared coordinate
    system changes, so draw.io lands on the true mm/pt sizes and 6 pt text stays 6 pt.

    For a fixed-figsize WYSIWYG canvas, do NOT pass ``bbox_inches="tight"`` -- it
    recrops the canvas and defeats the intended size; author the figure at its final
    ``figsize`` instead. It IS appropriate for a standalone figure whose goal is a
    tight crop (e.g. a legend-only image); the rescale still yields a correct
    physical size for whatever tight box matplotlib emits.
    """
    fig.savefig(path, **savefig_kwargs)
    with open(path, encoding="utf-8") as f:
        svg = f.read()
    # matplotlib always emits an <svg> root tagged with width/height in pt. If any of
    # these is missing the file is not a matplotlib SVG and the rescale is meaningless,
    # so fail loudly rather than silently writing a wrongly-sized figure.
    m_tag = re.search(r"<svg\b[^>]*>", svg)
    if m_tag is None:
        raise ValueError(f"{path}: no <svg> root tag; not a matplotlib SVG")
    open_tag = m_tag.group(0)
    m_w = re.search(r'width="([\d.]+)pt"', open_tag)
    m_h = re.search(r'height="([\d.]+)pt"', open_tag)
    if m_w is None or m_h is None:
        raise ValueError(f"{path}: <svg> root has no pt width/height to rescale")
    w = float(m_w.group(1))
    h = float(m_h.group(1))
    k = drawio_dpi / src_dpi
    new_w, new_h = w * k, h * k
    new_tag = re.sub(r'width="[\d.]+pt"', f'width="{new_w:.4f}"', open_tag)
    new_tag = re.sub(r'height="[\d.]+pt"', f'height="{new_h:.4f}"', new_tag)
    new_tag = re.sub(
        r'viewBox="[^"]*"', f'viewBox="0 0 {new_w:.4f} {new_h:.4f}"', new_tag
    )
    svg = svg.replace(open_tag, new_tag + f'<g transform="scale({k:.10f})">', 1)
    svg = svg.replace("</svg>", "</g></svg>", 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(svg)


def format_scientific_notation(num: float) -> str:
    """Format a number into scientific notation, preserving all significant digits.

    Examples:
        10000 -> "1e04"
        10007 -> "1.0007e04"
        1234567 -> "1.234567e06"
        100 -> "1e02"
    """
    if num == 0:
        return "0"

    # Handle negative numbers
    sign = ""
    if num < 0:
        sign = "-"
        num = abs(num)

    # Get exponent (power of 10)
    exponent = int(math.floor(math.log10(num)))
    mantissa = num / (10**exponent)

    # Find minimum precision needed to preserve the exact value
    mantissa_str = f"{mantissa:.0f}"  # Default for Pylance
    for precision in range(15):
        mantissa_str = f"{mantissa:.{precision}f}"
        reconstructed = float(mantissa_str) * (10**exponent)
        if round(reconstructed) == round(num):
            break

    # Clean up: remove trailing zeros and unnecessary decimal point
    mantissa_str = mantissa_str.rstrip("0").rstrip(".")

    return f"{sign}{mantissa_str}e{exponent:02d}"
