
biocypher:
  offline: true
  debug: false
  cache_directory: .cache

neo4j:
  delimiter: '\t'
  array_delimiter: '|'
  skip_duplicate_nodes: true
  skip_bad_relationships: true

  # Wipe DB before import (offline mode: --force)
  wipe: true

  database_name: torchcell
  uri: neo4j://localhost:7687
  user: neo4j
  password: torchcell
