# notes-tex/031-yeast-chemical-space/Makefile
# [[experiments.031-env-chemgen-inhibitor-tolerance]]
# https://github.com/Mjvolk3/torchcell/tree/main/notes-tex/031-yeast-chemical-space/Makefile
#
# `make` builds 031-yeast-chemical-space.pdf; `make check` runs the gate;
# `make plots` re-converts the two panels from ASSET_IMAGES_DIR.
#
# No Zotero collection yet: the works named are given by author and year in prose with an
# external flag, as 031-unified-representation does.

PYTHON ?= /home/michaelvolk/miniconda3/envs/torchcell/bin/python
PLOT_SLUGS := 031-env-chemgen-inhibitor-tolerance

include ../common/Makefile.common
