name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .env/requirements_docs.txt
          pip install git+https://github.com/pytorch/pytorch_sphinx_theme

      - name: Build the documentation
        run: |
          sphinx-build -b html docs build/docs

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs

  readthedocs:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Read the Docs Build
        run: |
          curl -X POST -d "" https://readthedocs.org/api/v2/webhook/your-project-name/your-webhook-token/
