name: MyPy Typing Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  mypy-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f env/mypy_requirements.txt ]; then pip install -r env/mypy_requirements.txt; fi
        python -m pip install -e .
        python -m pip install mypy

    - name: Check typing with MyPy
      run: |
        mypy src --config-file=mypy.ini
