name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f env/requirements.txt ]; then pip install -r env/requirements.txt; fi
        python -m pip install -e .
        python -m pip install mypy black

    - name: Check typing with MyPy
      run: |
        mypy src

    - name: Check formatting with Black
      run: |
        black --check src

    - name: Run pytest with coverage
      run: |
        cd tests
        coverage run -m pytest
        coverage xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
