name: Code Styling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  code-styling:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f env/requirements_style.txt ]; then pip install -r env/requirements_style.txt; fi
        python -m pip install -e .

    - name: Check formatting with Black
      run: |
        black src --check

    - name: Check import order with isort
      run: |
        isort src --check-only
