name: Code Styling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-styling:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f env/requirements.txt ]; then pip install -r env/requirements.txt; fi
        python -m pip install -e .
        python -m pip install black isort

    - name: Format with Black
      run: |
        black src

    - name: Order code with isort
      run: |
        isort src

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --exit-code || git commit -am "Automatically formatted with Black and isort" && git push
