name: Code Styling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  code-styling:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Please update to the latest available version

    - name: Set up Python
      uses: actions/setup-python@v2  # Please update to the latest available version
      with:
        python-version: 3.11  # Ensure this version is available

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f env/requirements_style.txt ]; then pip install -r env/requirements_style.txt; else echo "env/requirements_style.txt not found"; exit 1; fi
        python -m pip install -e .

    - name: Check code styling with flake8 and flake8-black
      run: |
        flake8 src --select BLK  # This will only run flake8-black. Remove --select BLK to run all flake8 checks
